version: 2
updates:
  - package-ecosystem: elm
    directory: '/'
    schedule:
      interval: daily
    rebase-strategy: 'disabled'
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    rebase-strategy: 'disabled'
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    rebase-strategy: 'disabled'
