name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [main]
    tags:
      - '*'

jobs:
  validate:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    env:
      example-dir: ./example

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: Install root dependencies
        run: yarn install --frozen-lockfile

      - name: Lint TS code
        run: yarn run eslint

      - name: Check formatting
        run: yarn run prettier

      - name: Type-check TS
        run: yarn run tsc

      - name: Install example dependencies
        run: yarn install --frozen-lockfile
        working-directory: ${{env.example-dir}}

      - name: Review Elm code
        run: yarn run review
        working-directory: ${{env.example-dir}}

      - name: Build example project
        run: yarn run build
        working-directory: ${{env.example-dir}}

  test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    env:
      example-dir: ./example

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: Install/Update dependencies
        run: yarn install --frozen-lockfile
        working-directory: ${{env.example-dir}}

      - name: Run tests
        run: yarn run test
        working-directory: ${{env.example-dir}}
