name: Publish Package
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    env:
      working-directory: ./example

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: Install/Update dependencies
        run: yarn install --frozen-lockfile
        working-directory: ${{env.working-directory}}

      - name: Review code
        run: yarn run build
        working-directory: ${{env.working-directory}}

  publish:
    runs-on: ubuntu-latest
    # Setup permissions for the GITHUB_TOKEN created for this workflow
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@PaackEng'

      - run: npm install

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
